/**
 * @file register.test.ts
 * Phase 5 — the consolidated issue register (the reveal deliverable).
 *
 * Aggregates the per-seed verdicts from the drill-down driver (engine/drill)
 * across the default seed batch into ONE severity-ranked, axis-categorised
 * register, each category carrying its reproducing seeds and a full named
 * root-cause report for a representative seed.
 *
 * The register is GENERATED, never hand-authored, so it can never drift from
 * the code that produces it.  It is printed to the console every run and, when
 * `WRITE_REGISTER=1` is set, written to fixtures/ISSUE_REGISTER.md as a
 * shareable artifact.  The only hard contract is that aggregation is
 * deterministic and covers every seed.
 */

import { describe, it, expect } from 'vitest'
import { drillSeed, type DecisiveKind } from './drill'

const DEFAULT_SEED_COUNT = 40
const SEED_COUNT = Number(process.env.SEED_COUNT) || DEFAULT_SEED_COUNT

/** Axis + severity metadata for each decisive verdict. */
const KIND_META: Record<
  DecisiveKind,
  { severity: number; axis: string; title: string }
> = {
  'FALSE-DEAD-MODAL': {
    severity: 1,
    axis: 'AXIS 1 — Liveness',
    title: 'Dead-game modal fires while legal moves remain',
  },
  'AI-MISSED-PROGRESS': {
    severity: 2,
    axis: 'AXIS 2/3 — Progress drift',
    title: 'AI idles though the oracle proves a productive move was available',
  },
  'AI-LOOP': {
    severity: 3,
    axis: 'AXIS 3 — Redundancy',
    title: 'AI livelocks, cycling without genuine progress',
  },
  'STUCK-CLEAN': {
    severity: 8,
    axis: 'AXIS 2/3 — Progress',
    title: 'AI stopped correctly: alive but no productive move (no issue)',
  },
  WON: { severity: 9, axis: '—', title: 'Game won (no issue)' },
  STOPPED: { severity: 9, axis: '—', title: 'Stopped, agrees dead (no issue)' },
}

const ISSUE_KINDS: DecisiveKind[] = ['FALSE-DEAD-MODAL', 'AI-MISSED-PROGRESS', 'AI-LOOP']

interface Bucket {
  kind: DecisiveKind
  seeds: string[]
  sampleReport: string
}

describe('consolidated issue register', () => {
  it(`aggregates ${SEED_COUNT} seeds into a severity-ranked register`, () => {
    const buckets = new Map<DecisiveKind, Bucket>()
    const outcomes: Record<string, number> = {}

    for (let i = 0; i < SEED_COUNT; i++) {
      const seed = `sim-${i}`
      const r = drillSeed(seed)
      outcomes[r.kind] = (outcomes[r.kind] ?? 0) + 1
      const b = buckets.get(r.kind) ?? { kind: r.kind, seeds: [], sampleReport: r.report }
      b.seeds.push(seed)
      buckets.set(r.kind, b)
    }

    const issues = ISSUE_KINDS.map((k) => buckets.get(k)).filter((b): b is Bucket => b != null)
    issues.sort((a, b) => KIND_META[a.kind].severity - KIND_META[b.kind].severity)

    const md = renderMarkdown(SEED_COUNT, outcomes, issues)

    // eslint-disable-next-line no-console
    console.log('\n' + md)

    if (process.env.WRITE_REGISTER) void writeArtifact(md)

    // Hard contract: every seed classified exactly once.
    const total = Object.values(outcomes).reduce((s, n) => s + n, 0)
    expect(total).toBe(SEED_COUNT)
  })
})

function renderMarkdown(
  seedCount: number,
  outcomes: Record<string, number>,
  issues: Bucket[],
): string {
  const L: string[] = []
  L.push('# Solitaire Logic — Issue Register (generated)')
  L.push('')
  L.push(
    `_Auto-generated by \`src/engine/__tests__/register.test.ts\` from the AI simulation ` +
      `harness + oracle. Do not edit by hand — regenerate with \`WRITE_REGISTER=1 pnpm test\`._`,
  )
  L.push('')
  L.push(`**Scope:** ${seedCount} seeded deals (\`sim-0\`…\`sim-${seedCount - 1}\`), draw-1, unlimited recycle.`)
  L.push('')
  L.push('**Outcome distribution (first decisive event per seed):**')
  L.push('')
  L.push('| Verdict | Seeds |')
  L.push('| --- | ---: |')
  for (const [kind, n] of Object.entries(outcomes).sort((a, b) => (KIND_META[a[0] as DecisiveKind]?.severity ?? 99) - (KIND_META[b[0] as DecisiveKind]?.severity ?? 99))) {
    L.push(`| ${kind} | ${n} |`)
  }
  L.push('')

  if (issues.length === 0) {
    L.push('No issues found. ✓')
    return L.join('\n')
  }

  L.push('## Issues (severity-ranked)')
  L.push('')
  issues.forEach((b, idx) => {
    const m = KIND_META[b.kind]
    L.push(`### ${idx + 1}. [${b.kind}] ${m.title}`)
    L.push('')
    L.push(`- **Axis:** ${m.axis}`)
    L.push(`- **Severity:** ${m.severity} (1 = highest)`)
    L.push(`- **Affected seeds (${b.seeds.length}):** ${b.seeds.map((s) => `\`${s}\``).join(', ')}`)
    L.push('')
    L.push('<details><summary>Representative root-cause drill</summary>')
    L.push('')
    L.push('```')
    L.push(b.sampleReport)
    L.push('```')
    L.push('')
    L.push('</details>')
    L.push('')
  })
  return L.join('\n')
}

/** Best-effort artifact writer; never throws into the test. */
async function writeArtifact(md: string): Promise<void> {
  try {
    const fs = await import('node:fs')
    const path = await import('node:path')
    const dir = path.resolve(__dirname, 'fixtures')
    fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(path.join(dir, 'ISSUE_REGISTER.md'), md + '\n')
  } catch {
    // ignore — artifact writing is a convenience, not a test contract
  }
}
